### ISSUE TITLE
How to play raw resource files which are inside the app folders in release mode?

### ISSUE THREAD

**Issue by ghost** [hyochan/react-native-audio-recorder-player#244]
### Put an audio file within your directory and pass its uri in startPlayer() method. 

I tried like this.
Image.resolveAssetSource(require('../audios/getlucky.mp3')).uri

Its working in debug build but not in release build.
Note: It's android specific.

**Comment by progsmile** [comment]
@abhishektiwari-kiwi do you have any updates regarding this?

**Comment by abhishektiwari-kiwi** [comment]
@progsmile Since my requirement changed and i was playing audios hosted on a server. So, i never really tried.
You can have a look at these for reference.
1. https://github.com/johnsonsu/react-native-sound-player
2. https://stackoverflow.com/questions/52476583/react-native-import-audio-file-from-android-res
3. https://github.com/react-native-kit/react-native-track-player/issues/967

Please let us know if it works for you.

**Comment by progsmile** [comment]
@abhishektiwari-kiwi Thanks for reply. I've used [react-native-audio-toolkit](https://github.com/react-native-audio-toolkit/react-native-audio-toolkit) library.

**Comment by hyochan** [comment]
Try use [rn-fetch-blob](https://www.npmjs.com/package/rn-fetch-blob) as told in the [README#tips](https://github.com/hyochan/react-native-audio-recorder-player#tips) for the file access.
