### ISSUE TITLE
No header support for iOS

### ISSUE THREAD

**Issue by dburdan** [hyochan/react-native-audio-recorder-player#356]
I didn't see it mentioned anywhere in the docs, but headers are not currently support on IOS. This can be misleading since the docs don't mention it and there are header Typescript types.

Is header support for iOS a planned feature?

**Comment by hyochan** [comment]
What do you exactly mean by the header support? Is this about the lock screen handler which appears in the notification?

**Comment by dburdan** [comment]
Sorry, I should have clarified I meant network headers. For example, if an audio file is on a server that requires an authorization header, this library can't play it on iOS.

**Comment by hyochan** [comment]
Oh yes! I remember that!. In version 2, it wasn't possible because the module was implemented with AVAudioPlayer which does not support `header`. However, I've done migration to `AVPlayer` which should be possible this day, but I've not had time to add that yet as done in `android`.

Maybe you can have a try on `PR`?

**Comment by dburdan** [comment]
Thanks for your quick feedback!

If I get some time over the next week, I'll see if I can create a PR for the headers. I'll also mention that it appears the play method on iOS doesn't properly reject any errors, so on the JS side there is no way to know if playback failed.
